### ISSUE TITLE
cf push fails to work with hwc-buildpack in PCF Dev

### ISSUE THREAD

**Issue by nathan-alden-inl** [cloudfoundry/hwc-buildpack#11]
Here's the command I used to create the buildpack in PCF Dev:
```
PS > cf create-buildpack hwc_buildpack https://github.com/cloudfoundry/hwc-buildpack/releases/download/v2.3.8/hwc-buildpack-v2.3.8.zip 10 --enable
Creating buildpack hwc_buildpack...
OK

Uploading buildpack hwc_buildpack...
Done uploading
OK
```
When I try and push a ASP.NET app targeting .NET Framework 4.6.2 from its `PublishOutput` folder, it fails:
```
PS > cf push devops-dotnetframework -b hwc_buildpack -s windows2012R2
Using stack windows2012R2...
FAILED
Stack windows2012R2 not found
```
I'm not sure what I'm doing wrong. The buildpack seems to have been imported just fine.

**Comment by nathan-alden-inl** [comment]
Do I need to somehow create the stack in PCF itself?
```
PS > cf stacks
Getting stacks in org pcfdev-org / space pcfdev-space as admin...
OK

name         description
cflinuxfs2   Cloud Foundry Linux-based filesystem
```

**Comment by sclevine** [comment]
PCF Dev does not support Windows stacks as they require Windows VMs that require Microsoft licensing. You can push .NET Core apps using the provided .NET Core buildpack.

A full PCF installation supports Windows stacks via the Windows Runtime Tile.

**Comment by nathan-alden-inl** [comment]
Okay, I suspected that. Thanks for the quick reply. :)
