### ISSUE TITLE
Release: hwc-buildpack (Mar)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/hwc-buildpack#112]
Release reminder for hwc-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/hwc-buildpack/compare/v3.1.28..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/hwc-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
There isn't anything much to need a release

**Comment by arjun024** [comment]
I notice that go used to build it has been updated https://github.com/cloudfoundry/binary-builder/pull/68 and a new version of hwc has come out. So let's include it and release

**Comment by arjun024** [comment]
https://github.com/cloudfoundry/hwc-buildpack/releases/tag/v3.1.29
