### ISSUE TITLE
manifest.yml is missing windows2016 stack

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/hwc-buildpack#12]
The automated commit to update the `hwc` binary removed the `windows2016` stack from the manifest: https://github.com/cloudfoundry/hwc-buildpack/commit/9f2d3d55118bf2adbf436eb6ee25656a6c96792c

**Comment by sclevine** [comment]
Thanks @sunjayBhatia, prioritized this along with a new release. Sorry for the trouble.

**Comment by sunjayBhatia** [comment]
Fixed as of: https://github.com/cloudfoundry/hwc-buildpack/commit/3f42275e0298b3a2a970e0f3230d46aa928e4005 and https://github.com/cloudfoundry/hwc-buildpack/releases/tag/v2.3.11
