### ISSUE TITLE
resolve a name (host) like IP

### ISSUE THREAD

**Issue by luizplago** [cloudfoundry/hwc-buildpack#29]
Hey there.

We need point an IP, for e.g.: 123.456.789.101, to a domain, for e.g.: external.test.

On development, we just set the hosts file as:  hosts
123.456.789.101	external.test

Sadly, I can’t just call the IP. I have to access it via external.test.

So, we tried ssh into the app and change the hosts:

console
echo 123.456.789.101 external.test >> c:\Windows\System32\drivers\etc\hosts" 

The return was:

console : Access is denied. 

Then we tried:

console
runas /user:admin "echo 123.456.789.101 external.test >> c:\Windows\System32\drivers\etc\hosts" 

But the return was:

console
RUNAS ERROR: Unable to run - echo 123.456.789.101 external.test >> c:\Windows\System32\drivers\etc\hosts 

1326: The user name or password is incorrect. 

Any ideas? How do I setup my hosts using cf/hwc-buildpack OR how can I run a command as admin inside the app?

Thanks in advance!

**Comment by menehune23** [comment]
@luizplago Closing this issue as stale. If it's still an issue for you, please feel free to reopen with detailed reproduction steps, and preferable a link to a minimal repo that reproduces the issue. Thank you!
